"""empty message

Revision ID: 5861fc8001f7
Revises: a380bd445932
Create Date: 2025-03-08 12:44:38.421714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5861fc8001f7'
down_revision = 'a380bd445932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=150), nullable=True),
    sa.Column('address_line_2', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=50), nullable=True),
    sa.Column('address_type', sa.Enum('Delivery', 'Billing', 'Unknown', name='addresstype'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
